templates/service.yaml
values.yaml

I'd like to be able to set annotations on the kubernetes service, so that I can automatically set AWS LB listener details as described in [this AWS doc](https://aws.amazon.com/premiumsupport/knowledge-center/terminate-https-traffic-eks-acm/)
This change just propogates service annotations set in values.yaml through to the service.yaml

Add service annotations

---

templates/ingress.yaml
values.yaml

Hello,
This PR allow users to configure additionally paths with arbitrary backend.
The main use case is to support ALB ingress controller redirect from HTTP to HTTPS as specified in this [AWS documentation](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/#redirect-traffic-from-http-to-https)
The values configuration for this scenario is
```yaml
ingress:
enabled: true
annotations:
kubernetes.io/ingress.class: alb
alb.ingress.kubernetes.io/scheme: internal
alb.ingress.kubernetes.io/backend-protocol: "HTTP"
alb.ingress.kubernetes.io/healthcheck-path: '/login/'
alb.ingress.kubernetes.io/success-codes: '200'
alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", …
```

Add support to adding arbitrary backends

---

README.md
templates/configmap.yaml
templates/deployment.yaml
templates/secret.yaml
values.yaml

Hello together,
as we require LDAP for authentication, we've implemented existing solutions of [netbox-docker](https://github.com/netbox-community/netbox-docker).
A slightly modified version of [ldap_config.py](https://github.com/netbox-community/netbox-docker/blob/release/configuration/ldap/ldap_config.py) is added in `templates/configmap.yaml`.
Is called by default via [ldap_config.docker.py](https://github.com/netbox-community/netbox-docker/blob/release/docker/ldap_config.docker.py).
Additional mappings for Variables -> netbox global configuration variables are added as `ldap.py` in `templates/configmap.yaml`.
Are loaded via via [configuration.docker.py](https://github.com/netbox-community/netbox-docker/blob/release/docker/configuration.docker.py#L28).
As the underlying module is …

Added LDAP support

---

README.md
templates/deployment.yaml
templates/worker-deployment.yaml
values.yaml

For our use case it is to support Azure aad-pod-identity as it uses a pod label to do the binding:
https://azure.github.io/aad-pod-identity/docs/demo/standard_walkthrough/#6-deployment-and-validation

Add pod labels support

---

templates/_helpers.tpl
templates/configmap.yaml
templates/deployment.yaml
templates/hpa.yaml
templates/ingress.yaml
templates/pvc-media.yaml
templates/pvc-reports.yaml
templates/secret.yaml
templates/service.yaml
templates/serviceaccount.yaml
templates/worker-deployment.yaml
templates/worker-hpa.yaml
values.yaml

This PR adds the ability to set custom labels and custom annotations on any resource generated by the chart (not subchart !) with the dictionnaries `commonLabels` and `commonAnnotations`, empty by default.
Partially fixes #60 (pod labels are not covered by my PR as long as it is not a direct resource generated by the chart and covered by https://github.com/bootc/netbox-chart/commit/198e74703345902cda043f850ca273ec47811b40)
* For the labels, I used the helper.tpl `netbox.labels` which is already in all resources (except worker-hpa). I added this at the end of the template function
```
{{- with .Values.commonLabels }}
{{ toYaml . }}
{{- end }}
```
For worker-hpa I added this in labels :
```
{{- with .Values.commonLabels }}
{{- toYaml . | nindent 4 }}
{{- end }}
```
* For the annotations, I …

feat(values): add commonLabels and commonAnnotations

---

Chart.yaml
templates/_helpers.tpl

fix: get secret name for redis and postgresql from existingSecret if configured

---

templates/cronjob.yaml

Fix for cronjob.yaml indentation problem when imagePullSecrets is specified.

Fix indentation for imagePullSecrets in CronJob template

---

README.md
values.yaml

In the README.md
- Add a chapter on how to use extraConfig for S3 storage configuration
- Complete the list of existingSecret credential keys
In the values.yaml
- Add some comments on the use of existingSecret

Improve README and add some comments in values

---

README.md
templates/deployment.yaml
values.yaml

This PR aims to allow for more flexibility in the readiness probe configuration. This was causing events in our NetBox set up and allowing for a longer timeout resolved this.

Make readiness probe configurable

---

templates/configmap.yaml

Since PostgreSQL 10 the C library libpq, that is used by psycopg, that itself is used in Django and therefore NetBox, supports specifying multiple PostgreSQL hosts and a kind of selector.
See these links:
* https://www.postgresql.org/docs/14/libpq-connect.html#LIBPQ-CONNSTRING
* https://www.postgresql.org/docs/14/libpq-connect.html#LIBPQ-CONNECT-TARGET-SESSION-ATTRS
Basically one is able to specify multiple hosts and what a session to a host should support.
libpq will then try each host and use first matching one.
In the case of an aborted connection or if a failover happens, the application will still get an error, but is able to retry and a new host will be searched for automatically.
The added option in this PR is compatible to single hosts as well.
And it makes sense to set as …

Added libpq option target_session_attrs for cluster support

---

Chart.yaml
templates/deployment.yaml

https://github.com/bootc/netbox-chart/pull/81 breaks the helm chart when
a value for `.Values.allowedHosts` is used. `httpHeaders` is a subkey of
`httpGet` and the newly added values are siblings of `httpGet`. Putting
those new values between `httpGet` and `httpHeaders` breaks the position
and indentation of `httpHeaders`.
As a solution this commit moves the new values after `httpHeaders`.

Fix allowedHosts which is broken since 4.1.0

---

Chart.yaml
README.md
templates/servicemonitor.yaml
values.yaml

The Prometheus-Operator is a popular choice for collecting metrics, and many other projects (such as External-DNS [1]) have a pre-configured ServiceMonitor resource ready to be enabled; this does the same for Netbox.
The template is very heavily inspired by the External-DNS one.
1: https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/templates/servicemonitor.yaml

Create optional ServiceMonitor for Netbox

---

README.md
docs/auth.md

I have added docs with configuration examples for Keycloak and GitLab as SSO backends.
Closes #110.

add examples for sso backend config

---

templates/deployment.yaml
templates/worker-deployment.yaml

Fix: Deployment Failure when using hostAliases closes #128 and use `nindent` instead.

Fix: Deployment Failure when using hostAliases

---

templates/configmap.yaml
values.yaml

We experienced connection errors between netbox and postgresql pgpool service (`postgresql-ha` bitnami helm chart). The following error occurred in UI:
The following error message was in the log:
```
Internal Server Error: /virtualization/interfaces/
Traceback (most recent call last):
File "/opt/netbox/venv/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py", line 187, in _get_session
return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
self.connect()
File …
```

Add ability to set target_session_attrs value for externalDatabase

---

templates/configmap.yaml
templates/deployment.yaml
values.yaml

To simplify Prometheus metrics gathering (refs issue #166).

Allow PodIP to be included as part of the ALLOWED_HOSTS setting

---

README.md
templates/configmap.yaml
values.yaml

This PR adds the option `REMOTE_AUTH_AUTO_CREATE_GROUPS` which is useful for while using remote authentication.
All options are documented [here](https://docs.netbox.dev/en/stable/configuration/remote-authentication/#remote_auth_auto_create_groups).

adding support for create groups via remote authentication

---

templates/serviceaccount.yaml
values.yaml

Provides the option to set the `imagePullSecrets` on the ServiceAccount instead of the deployment.

Add 'serviceAccount.imagePullSecrets' option.

---

.github/workflows/analysis.yml
.github/workflows/ci.yml

Just realized the default branch on #181 was not the correct one.
This PR fixes this.

Fix default branch for GitHub Actions workflows

---

.github/workflows/release.yml

Second fix after #181 to make GitHub Actions run.

Remove the unused secret variable for GHA

---

charts/netbox/Chart.lock
charts/netbox/Chart.yaml
charts/netbox/templates/NOTES.txt
charts/netbox/templates/_helpers.tpl
charts/netbox/templates/configmap.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/hpa.yaml
charts/netbox/templates/ingress.yaml
charts/netbox/templates/pvc-media.yaml
charts/netbox/templates/pvc-reports.yaml
charts/netbox/templates/secret.yaml
charts/netbox/templates/service.yaml
charts/netbox/templates/serviceaccount.yaml
charts/netbox/templates/servicemonitor.yaml
charts/netbox/templates/tests/test-connection.yaml
charts/netbox/templates/worker-deployment.yaml
charts/netbox/templates/worker-hpa.yaml

This pull request suggests using [Bitnami `common` chart](https://github.com/bitnami/charts/tree/main/bitnami/common) to significantly simplify maintenance while increasing the standardization.
It could help generate proper labels, annotations, names, and attributes that match the latest Kubernetes operators expectations.
> [!note]
> This PR is only bringing a subset of the helpers Bitnami's common is provided.
> It is to ensure we agree on the principle before further implmenetation.
> 
> Additionnal helpers includes:
> * Labels & Annotations proper merging
> * Security & Resources helpers
> * Compatibility helpers
---
Direct follow up of https://github.com/netbox-community/netbox-chart/issues/162#issuecomment-2061528891

Leverage Bitnami `common` chart helpers

---

README.md
charts/netbox/Chart.yaml
charts/netbox/templates/configmap.yaml
charts/netbox/values.yaml

Support setting `DATA_UPLOAD_MAX_MEMORY_SIZE` and `FILE_UPLOAD_MAX_MEMORY_SIZE` in configmap.

feat: add settings for controlling http message sizes

---

README.md
charts/netbox/Chart.yaml
charts/netbox/templates/_helpers.tpl
charts/netbox/templates/configmap.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/service.yaml
charts/netbox/templates/serviceaccount.yaml
charts/netbox/templates/servicemonitor.yaml
charts/netbox/templates/worker-deployment.yaml
charts/netbox/values.yaml

The goal of this PR is to give the `values.yaml` a sectioned structure to ease its reading and its maintenance.
The following objectives are in mind:
* Add standard global parameters (used across more and more charts)
* Document all values as much as possible
* Gives all values a formatted comment
* It follows Bitnami's standard
* That will help to auto-generate docs as a next step
* With something that can use on tools like https://artifacthub.io/
* Eventually get rid of the cumbersome to maintain README's list
* Regroup parameters per scope
* Global
* Common
* NetBox Image
* NetBox Configuration
* Deployment
* Traffic Exposure
* Metrics
* Databases
* Autoscaling
* Volume permissions / Init
* Test
* Housekeeping
* Worker
> [!note]
> Despite the high number of line changed, very few …

Reorder values and their documentation

---

charts/netbox/Chart.yaml
charts/netbox/templates/configmap.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/secret.yaml
charts/netbox/templates/worker-deployment.yaml

First helm related commit, so be gentle. :p 
In the new 5.0 release, remoteAuth.backend is deprecated and you have to specify both remoteAuth.backend and remoteAuth.backends to get a working LDAP configuration. 
This PR aims to fix that by removing all references to remoteAuth.backend.

Changed Templates to use the new remoteAuth.backends array, instead of .backend

---

charts/netbox/Chart.yaml
charts/netbox/templates/deployment.yaml

Attempting to use `beta8` was failing with the following error:
```shell
$ helm template netbox netbox/netbox --devel --values values.yaml -s templates/deployment.yaml        
Error: YAML parse error on netbox/templates/deployment.yaml: error converting YAML to JSON: yaml: line 135: did not find expected key
```
After some troubleshooting, I worked out that this is the issue and have now successfully rendered templates locally.

fix: correct indentation of extraVolumeMounts

---

charts/netbox/Chart.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/tests/test-connection.yaml
charts/netbox/templates/worker-deployment.yaml

This PR enforces template rendering for `resources`, `initContainers` and `sidecars` accross the chart.
This would make it less prone to configuration/user input errors.

Streamline rendering for `resources`, `initContainers` and `sidecars`

---

README.md

Updated documentation to point to new helm chart repo.

---

charts/netbox/Chart.yaml
charts/netbox/templates/cronjob.yaml

The housekeeping CronJob produces an invalid spec when image pull secrets are set as the indent is wrong.

Fix indent for housekeeping CronJob imagePullSecrets

---

charts/netbox/Chart.yaml

I found when trying to depend on this chart that `helm dep update` didn't consider beta14 higher than beta9. This should hopefully make it update properly.

add a dot to the beta so it sorts numerically

---

charts/netbox/Chart.yaml
charts/netbox/values.yaml

This PR is switching the default registry for Netbox image from Docker Hub (`docker.io`) to GitHub Container Registry (`ghcr.io`).
The motivations are the following:
* GHCR is 100% free of use for egress, with almost nonexistent limits compared to Docker Hub. This helps to reduce rate limit errors of large deployments.
* Download speed is slightly better, especially for development in the GitHub context (mainly GitHub Codespaces and GitHub Actions)
* Container images management on GHCR is more transparent for other repositories as this one. 
* The content is the same.

Use GitHub Container Registry as default registry for main image

---

README.md
charts/netbox/Chart.yaml
charts/netbox/templates/_helpers.tpl
charts/netbox/templates/deployment.yaml
charts/netbox/templates/postgresql-secret.yaml
charts/netbox/templates/redis-secret.yaml
charts/netbox/templates/secret.yaml
charts/netbox/templates/superuser-secrets.yaml
charts/netbox/templates/worker-deployment.yaml
charts/netbox/values.yaml

This PR aims to facilitate secret values management.
By splitting them into per-domain secret instances, proper management policies can be applied.
It should also help to have consistent secrets in the time and across deployments, and ease secret instance deprecation.

Split secrets values across segmented secrets instances

---

.github/renovate.json

This is quite a workaround, but makes sure to follow Helm chart recommendations on versioning ranges.
Also migrate configuration to the latest schema.

Fix Renovate config for OCI repositories

---

charts/netbox/Chart.yaml
charts/netbox/templates/configmap.yaml
charts/netbox/templates/deployment.yaml

Reference: 
* Closes #254
Currently, `allowedHostsIncludesPodIP ` does not work as intended due to incorrect capitalization and an indentation mistake.

Fix `allowedHostsIncludesPodIP`

---

charts/netbox/Chart.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/worker-deployment.yaml

This PR fixes issue #261 
---
Deploy the helm chart with `scriptsPersistence.enable: true` results in `netbox-worker` and `housekeeping` (cronjob) generated with illegal k8s yaml spec
---
Fix the `cronjob.yaml` and `worker-deployment.yaml` helm templates.

Fix deployment issue if script persistence is enabled

---

charts/netbox/Chart.yaml
charts/netbox/templates/worker-deployment.yaml

With this adjustments the `global.imagePullSecrets` and the `image.pullSecrets` will fill the `imagePullSecrets` in the worker deployment manifest.
Also now the filling of the `imagePullSecrets` in the worker deployment will have the same behavior as in the netbox deployment and the cronjob manifest.

Take all imagePullSecrets in the worker deployment into account

---

.github/renovate.json

This fixes the missing chart version bump when a dependency is updated.
> [!tip]
> I'd recommend not to merge before chart 5.0.0 is published.

Use proper Renovate manager matcher

---

README.md
charts/netbox/Chart.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/values.yaml

This aims to add all the necessary probes to ensure stable deployments.
It would have been great to have an alternative probe with an exec scheme instead, bot Netbox does not seem to provide status check via CLI.
Also, add the customization capability, so users can set up their probes based on plugins, for example.
Fixes #100 
> [!note]
> Upgrade test fail as it would require major version bump

Setup all Kubernetes probes for dep stability

---

charts/netbox/Chart.yaml
charts/netbox/templates/worker-deployment.yaml

At the moment podAffinity is created with wrong indentation. For example 
---
`extraVals.yml`
```yaml
worker:
affinity:
podAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchLabels:
app.kubernetes.io/name: netbox
topologyKey: kubernetes.io/hostname
```
```shell
helm template -s templates/worker-deployment.yaml netbox . -f extraVals.yml
.
.
REDACTED_FOR_KEEPING_FOCUS_ON_THE_PROBLEM
.
.
- name: media
persistentVolumeClaim:
claimName: netbox-media
affinity:
podAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchLabels:
app.kubernetes.io/name: netbox
topologyKey: kubernetes.io/hostname
```
with the change it generates the template as it follows 
```shell
helm template -s templates/worker-deployment.yaml netbox . -f extraVals.yml
.
.
. …
```

Fix for affinity indentation

---

README.md
charts/netbox/Chart.yaml
charts/netbox/templates/configmap.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/worker-deployment.yaml
charts/netbox/values.yaml
docs/auth.md

This PR support for custom CA certificates when using LDAP authentication. Users can now provide their own CA certificates in the caCertData value, which will be mounted as a file in the container. As this is my first contribution to this project, I am open to any feedback or suggestions for improvement. 
Closes #119

Add support for bringing your own LDAP CA certificate

---

charts/netbox/Chart.yaml
charts/netbox/templates/configmap.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/worker-deployment.yaml

It looks like this didn't work out. It looks like the reference got wrong if there is a range. If we use `$` it access the root data object.
```
Helm install failed for release netbox/netbox with chart netbox@5.0.0-beta.71: template: netbox/templates/worker-deployment.yaml:28:28: executing "netbox/templates/worker-deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: netbox/templates/configmap.yaml:296:18: executing "netbox/templates/configmap.yaml" at <.Values.remoteAuth.ldap.caCertData>: can't evaluate field Values in type interface {}
```
Ref #293

Fix caCertData to use root data object instead of current context

---

charts/netbox/Chart.yaml
charts/netbox/templates/configmap.yaml

- It looks like a pipe symbol was added at the top of the ldap_ca.crt data file
I think that the `nindent` can cause this as it prepends a new line.
Cert data was defined like this:
```
caCertData: |
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```
Output in the ldap_ca.crt file:
```
ldap_ca.crt: |-
|
-----BEGIN CERTIFICATE-----
```

Fix indentation of ldap_ca.crt data

---

README.md
charts/netbox/Chart.yaml

With https://github.com/netbox-community/netbox-chart/pull/301 the Redis helm chart got updated to 20.x.x, but the README still mentions version 19.x.x.

Correct redis version used in 5.x release in README.md

---

.editorconfig
.flake8
.github/workflows/lint.yml
charts/netbox/Chart.yaml
charts/netbox/files/configuration.py
charts/netbox/files/ldap_config.py
charts/netbox/templates/configmap.yaml
pyproject.toml

The purpose of this PR is to isolate Python files used in the Helm chart to apply usual tests and checks on them.
This should help to maintain these scripts:
* Automatic lint/format/assertions based on Netbox org config (#326).
* Better dev environment with Python-related IDE extensions and integrations.
* Possibility to add integration tests, which could help to assess contributions like #318.
* Same features from Helm chart point of view.
From a more opinionated PoV, I believe keeping Python files away from Helm chart templating would ensure more stable scripts and less breaking changes there.

Split Python files from ConfigMap

---

charts/netbox/Chart.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/values.yaml

Follow up of #244
This PR should improve the use of Kubernetes probes.
* Nginx status checking if the pod is still live (liveness)
* `/login` response checking if the app is still responsive (readiness, unchanged)
* `/login` response checking if the app startup is done (startup)
* Should help to take care of migrations at startup
* Follow up of https://github.com/netbox-community/netbox-docker/pull/1203 & https://github.com/netbox-community/netbox-docker/pull/1233

Fix liveness and startup probes

---

charts/netbox/Chart.yaml
docs/auth.md

The "backend" property in "remoteAuth" has been replaced with "backends"

Update documentation for new values.yaml format

---

charts/netbox/Chart.yaml
docs/auth.md

Hello ! 
The doc was not working to add a keycloak SSO integration, So we correct it and we want to update it !
Best regards.

Add some correction in the Auth tutorial for Keycloak

---

charts/netbox/Chart.yaml
charts/netbox/templates/configmap.yaml

When using the externalDatabase option, the config.yaml is being broken by the newline removal in the else statement of the Jinja2 template:
netbox.yaml:
----
ALLOWED_HOSTS: ["*"]
ALLOWED_HOSTS_INCLUDES_POD_ID: true
DATABASE:HOST: "postgres-netbox"
USER: "netbox"
NAME: "netbox"
PORT: 5432

Fix `externalDatabase` config templating

---

charts/netbox/values.schema.json
charts/netbox/values.yaml

This PR adds the `values.schema.json` file.
It is the [standard schema file](https://helm.sh/docs/topics/charts/#schema-files) for values validation.
The proposed version is relatively naive, auto-generated and without further customization.

Add a schema for values validation

---

charts/netbox/Chart.yaml
charts/netbox/values.schema.json

Hi,
Your helm chart [theoretically accepts object types](https://github.com/netbox-community/netbox-chart/blob/4242df109d52e55abe5db0c8ae4746385a0ebc1a/charts/netbox/templates/ingress.yaml#L32-L38) for ingress paths, however the json schema currently only allows strings. 
This PR changes the schema so both `string` and `object` types are allowed.

fix: allow object types for ingress paths

---

charts/netbox/Chart.yaml
charts/netbox/templates/_helpers.tpl
charts/netbox/values.schema.json
charts/netbox/values.yaml

This change makes LDAP values part of the default values.
While this has zero impact on the chart behavior, this allows to enforce additional checks and validations.
It also helps to provide an appropriate schema.

LDAP values available per default

---

charts/netbox/Chart.yaml
charts/netbox/templates/_helpers.tpl
charts/netbox/templates/configmap.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/secret.yaml
charts/netbox/templates/tests/test-connection.yaml
charts/netbox/templates/worker/deployment.yaml
charts/netbox/values.schema.json
charts/netbox/values.yaml

Tweak YAML rendering using common render helpers, and resolves https://github.com/netbox-community/netbox-chart/issues/403.
Helps to reduce mistake surface in the rendering.
Also add `extraEnvVarsCM` and `extraEnvVarsSecret` as shortcuts to gather vars from CM or Secret directly.

Tweak YAML rendering using common render helpers

---

charts/netbox/Chart.yaml
charts/netbox/templates/_helpers.tpl
charts/netbox/templates/configmap.yaml

Fix incorrect format string template for `extraConfig` (`%s` -> `%d`) part 2

---

charts/netbox/Chart.yaml
charts/netbox/templates/_helpers.tpl
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/secret.yaml
charts/netbox/templates/worker/deployment.yaml
charts/netbox/values.yaml

Noticed that this was one of the only credentials I couldn't slap into an external secret and source from the chart. This should allow that functionality. I did test locally and it looked like it put the value in all of the right places. Didn't find a whole lot about guidelines on contributing, so let me know if there's anything additional I need to do. Thanks!

External secret for email password

---

charts/netbox/Chart.yaml
charts/netbox/values.yaml

While setting up NetBox with the Helm chart, I observed crashes even as the sole user on a fresh, empty instance. 
These "crashes" were caused by the OOM killer, as the small resourcePreset with 768Mi memory was insufficient.
Memory usage sometimes spiked during basic operations, leading to process termination. 
Switching to the medium preset resolved the issue, and I have not experienced issues since.
Although I understand it's good practice to keep resource preset as low as possible, the current default may confuse novice users who might not understand why their application is unstable. 
Changing the default to medium could provide a more robust out-of-the-box experience.

Suggestion: Update the default resourcePreset to medium

---

charts/netbox/Chart.yaml
charts/netbox/templates/deployment.yaml

As title, indent got bumped to 10 in #405 (cdd50ae) and it's one level too many.

Fix deployment `extraEnvs` template indent

---

charts/netbox/Chart.yaml
charts/netbox/values.schema.json
charts/netbox/values.yaml

Resolves https://github.com/netbox-community/netbox-chart/issues/436

Fix wrong types in `values.schema.json`

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/test.yml
README.md
charts/netbox-operator/.helmignore
charts/netbox-operator/Chart.lock
charts/netbox-operator/Chart.yaml
charts/netbox-operator/README.md
charts/netbox-operator/ci/default-values.yaml
charts/netbox-operator/crds/ipaddressclaims.yaml
charts/netbox-operator/crds/ipaddresses.yaml
charts/netbox-operator/crds/prefixclaims.yaml
charts/netbox-operator/crds/prefixes.yaml
charts/netbox-operator/templates/NOTES.txt
charts/netbox-operator/templates/_helpers.tpl
charts/netbox-operator/templates/clusterrole.yaml
charts/netbox-operator/templates/clusterrolebinding.yaml
charts/netbox-operator/templates/deployment.yaml
charts/netbox-operator/templates/leaderelect/role.yaml
charts/netbox-operator/templates/leaderelect/rolebinding.yaml
charts/netbox-operator/templates/secret.yaml
charts/netbox-operator/templates/serviceaccount.yaml
charts/netbox-operator/templates/servicemonitor.yaml
charts/netbox-operator/values.yaml

This PR implements a Helm chart for the [NetBox Operator](https://github.com/netbox-community/netbox-operator).
Resolves https://github.com/netbox-community/netbox-operator/issues/105
```[tasklist]
```

Init NetBox Operator Helm chart

---

charts/netbox/Chart.yaml
docs/auth.md

The current scripts provided for keycloak and gitlab, require the `client_id` to be configured in the script as well as the config values for social auth.
This pull request, adapts the script slightly, to read the `client_id` from django.settings, ensuring that the same value is used, as configured for social auth.
Additionally two more fields are introduced, to make the mapping of staff/superuser roles configurable.

Improve auth `sso_pipeline_roles` script with Django settings

---

.github/workflows/lint.yml
docs/migrate.md

Adding a migration guide on how to migrate from bootc/netbox-chart to netbox-community/netbox-chart
I can also add all the ArgoCD specific parts if this is of any interest

docs: add migration guide from bootc/netbox-chart to netbox-community/netbox-chart

---

charts/netbox/Chart.yaml
charts/netbox/README.md
charts/netbox/templates/configmap.yaml
charts/netbox/values.schema.json
charts/netbox/values.yaml

The `sslrootcert` parameter specifies the name of a file containing SSL certificate authority (CA) certificate(s). If the file exists, the server's certificate will be verified to be signed by one of these authorities (in the case of an SSL connection to the PostgreSQL DB).
See the option in the documentation here: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLROOTCERT
Resolves #417

Improve database client options templating

---

.github/workflows/ci.yml

This will help to (auto-)merge PR when the charts are not affected.
> [!note]
> This requires changing the repository branch ruleset for pull requests required checks to only "Status" action.

Add a generic status steps when chart CI is not required

---

charts/netbox/Chart.yaml
charts/netbox/values.schema.json
charts/netbox/values.yaml

This fixes an error likely introduced in 04c18cd which prevents configuring a working LDAP setup with this chart.
Currently the chart forces `mirrorGroupsExcept` to be a string which results in Netbox throwing the following error when trying to log in:
```
<class 'django.core.exceptions.ImproperlyConfigured'>
AUTH_LDAP_MIRROR_GROUPS_EXCEPT must be a collection of group names
```
With the proposed change, the correct type is set in the schema and a sensible default in the `values.yaml` is added.

Fix LDAP values types

---

charts/netbox/Chart.yaml
charts/netbox/README.md
charts/netbox/templates/configmap.yaml
charts/netbox/values.schema.json
charts/netbox/values.yaml
docs/auth.md

Add support for missing LDAP configuration option [LDAP_CA_CERT_DIR](https://github.com/netbox-community/netbox/issues/9722)

Add support for `LDAP_CA_CERT_DIR`

---

charts/netbox/Chart.yaml
charts/netbox/templates/deployment.yaml

This would ensure Secrets/ConfigMaps annotation are ignored for the checksums.

Use common helpers for checksums

---

charts/netbox/Chart.yaml
charts/netbox/README.md
charts/netbox/values.yaml

'enforceGlobalUnique' default behavior changed from 'false' to 'true' in Netbox 3.7.0 (See https://github.com/netbox-community/netbox/issues/14536).  This PR updates the Helm chart default values to reflect this change in behavior.

Set `enforceGlobalUnique` default to `true`

---

charts/netbox/Chart.yaml
charts/netbox/files/configuration.py

This PR adds a new value `customSecretMount` which is false by default. If `customSecretMount: true` is set, volumeMounts and volumes regarding secrets are excluded from the generated templates. Leaving it up to the user to define extraVolumes and extraVolumeMounts to define secrets.
This feature is needed when the chart user defines custom volumes for secrets (ex. when using [Secrets Store CSI Driver](https://secrets-store-csi-driver.sigs.k8s.io/)) instead of relying on kubernetes secrets or environment variables.
The definition of volumes and volumeMounts regarding `/run/secrets/` have been moved into a `{{- if (eq .Values.customSecretMount false) }}` block.
`customSecretMount` could also be changed to a variable name like `usePasswordFiles` similar to the [postgresql chart …

Allow for manual mounting of secrets

---

charts/netbox-operator/Chart.yaml
charts/netbox-operator/templates/deployment.yaml
charts/netbox-operator/values.yaml

Fixes #602
Also clarify `caCert` value by renaming it `caCertPath`.

Add volume placeholders for operator deployment

---

charts/netbox/Chart.yaml
charts/netbox/templates/role.yaml
charts/netbox/templates/rolebinding.yaml
charts/netbox/templates/worker/deployment.yaml
charts/netbox/values.schema.json
charts/netbox/values.yaml

> [!note]
> Kinda big feature and bring a additionnal container image to the chart, thus bumping minor version.
1. Increase startup probe failure threshold
2. Add an initial container to the worker deployment so it waits for main deployment to be ready before spinning in.
Fixes #581

[v6] Prevent failures and restarts of deployments

---

charts/netbox/Chart.lock
charts/netbox/Chart.yaml
charts/netbox/README.md
charts/netbox/files/configuration.py
charts/netbox/templates/_helpers.tpl
charts/netbox/templates/configmap.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/secret.yaml
charts/netbox/templates/worker/deployment.yaml
charts/netbox/values.schema.json
charts/netbox/values.yaml

Follow up of https://github.com/netbox-community/netbox-docker/pull/1203
Bitnami chart: https://github.com/bitnami/charts/tree/HEAD/bitnami/valkey
---

[v6] Switch from Redis to Valkey

---

charts/netbox/Chart.lock
charts/netbox/Chart.yaml
charts/netbox/README.md
charts/netbox/files/configuration.py
charts/netbox/templates/_helpers.tpl
charts/netbox/templates/configmap.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/role.yaml
charts/netbox/templates/rolebinding.yaml
charts/netbox/templates/secret.yaml
charts/netbox/templates/worker/deployment.yaml
charts/netbox/values.schema.json
charts/netbox/values.yaml

Milestone: https://github.com/netbox-community/netbox-chart/milestone/5
---
```md
- NetBox has been updated to version 4.3 which introduces some configuration changes.
- `storageBackend` and `storageConfig` have been dropped in favor of the new `storages` (https://github.com/netbox-community/netbox-chart/pull/656).
- `externalDatabase` now defines the default database (non-breaking), while additional databases can be set using `additionalDatabases` (https://github.com/netbox-community/netbox-chart/pull/659)
- The Bitnami [Redis](https://github.com/bitnami/charts/tree/main/bitnami/redis) sub-chart has been replaced by the Bitnami [Valkey](https://github.com/bitnami/charts/tree/main/bitnami/valkey) sub-chart (https://github.com/netbox-community/netbox-chart/pull/332).
- If `redis.enabled` …
```

Release v6.0.0

---

charts/netbox/Chart.yaml
charts/netbox/values.schema.json

TL;DR
-----
Allows templated strings for `extras` in the `values.yaml` file
Details
-------
Lets users advantage of the underlying `common.tplvalus.render`
function used to render `extraEnvs`, `extraVolumes`, and
`extraVolumeMounts` by opening up the values schema so that either a
string or an array can be passed in for those values.

Updates schema to support string extras

---

charts/netbox/Chart.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/values.schema.json
charts/netbox/values.yaml

Add timezone parameter for housekeeping cronjob
By default cronjob run in UTC timezone and it's little be confusing sometimes and can be customized
According [this](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones) reference manual we can set timezone param since kubernetes 1.27 version

Add timezone parameter for housekeeping cronjob

---

charts/netbox/Chart.yaml
charts/netbox/templates/_helpers.tpl

When using external sentinels, the generated YAML looks something like this:
```
REDIS:
tasks:
SENTINELS: [netbox-redis-ha-announce-0:26379 netbox-redis-ha-announce-1:26379 netbox-redis-ha-announce-2:26379]
```
This PR fixes it so it looks like this:
```
REDIS:
tasks:
SENTINELS: ["netbox-redis-ha-announce-0:26379","netbox-redis-ha-announce-1:26379","netbox-redis-ha-announce-2:26379"]
```
And thus, external sentinels can be used again.

Fix using external sentinels
