README.md
templates/service.yaml
values.yaml

fixes #8 
I haven't done any Helm templating for a while, so I hope it's okay 😄

Add support for loadBalancerSourceRanges in k8s service

---

README.md
templates/configmap.yaml
values.yaml

Add additonal remote auth settings

---

README.md

Add example to show how you might configure SSO

---

templates/configmap.yaml
values.yaml

add CSRF support..

---

templates/deployment.yaml
templates/worker-deployment.yaml
values.yaml

adding hostAliases to deployment and worker.

adding hostAliases to deployment and worker

---

templates/tests/test-connection.yaml
values.yaml

I would like to be able to specify the image to be used for the connection test as well as its resources.

make test-connection more configurable (image & resources) 

---

README.md

This supersedes #89 and closes #70. Add a README section explaining how to deal with configuring persistent storage for image uploads.

README.md: add note about persistent storage

---

README.md
templates/cronjob.yaml
templates/deployment.yaml
templates/serviceaccount.yaml
templates/worker-deployment.yaml
values.yaml

Set the `automountServiceAccountToken` to false

---

.github/dependabot.yml
.github/renovate.json
.github/workflows/auto-merge.yml

This change would help to maintain the app up-to-date on its dependencies.
This includes upstream NetBox container image version.
Direct follow up of https://github.com/netbox-community/netbox-chart/issues/162#issuecomment-2061528891

Enable bots/apps for automatic dependencies updates

---

charts/netbox/Chart.yaml
charts/netbox/templates/NOTES.txt
charts/netbox/templates/configmap.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/hpa.yaml
charts/netbox/templates/ingress.yaml
charts/netbox/templates/pvc-media.yaml
charts/netbox/templates/pvc-reports.yaml
charts/netbox/templates/secret.yaml
charts/netbox/templates/service.yaml
charts/netbox/templates/serviceaccount.yaml
charts/netbox/templates/servicemonitor.yaml
charts/netbox/templates/worker-deployment.yaml
charts/netbox/templates/worker-hpa.yaml

Using Bitnami common helpers from #184 to provide the following:
* Correctly namespaced entities
* Labels and annotations with proper merging function (to avoid duplications and errors)
* More validations around metadata (length of names is crucial, as much as other structure)

Add standard namespace and metadata

---

charts/netbox/Chart.yaml
charts/netbox/templates/ingress.yaml

Render a proper backend definition for ingress

---

charts/netbox/Chart.yaml

will move to 4 once the docker image is available

bump to NetBox 4.0.0

---

charts/netbox/Chart.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/tests/test-connection.yaml
charts/netbox/templates/worker-deployment.yaml
charts/netbox/values.yaml

Fix https://github.com/netbox-community/netbox-chart/issues/203

Streamline rendering for security contexts

---

charts/netbox/Chart.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/worker-deployment.yaml
charts/netbox/values.yaml

Add revisionHistoryLimit to deployments

---

README.md
charts/netbox/Chart.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/worker-deployment.yaml
charts/netbox/values.yaml

Add scriptsPersistence

---

charts/netbox/values.yaml

Fix inline doc typo

---

charts/netbox/Chart.yaml
charts/netbox/templates/pvc-scripts.yaml

It looks like creating the PersistentVolumeClaim itself was missed in PR 224, so this adds onto that.

Add scriptsPersistence PVC

---

charts/netbox/Chart.yaml
charts/netbox/templates/cronjob.yaml

Ensure correct default secret name for housekeeping

---

docs/auth.md

My Python is a bit rusty, but I _think_ this will work?

update examples to use the NetBox 4.x plugin API

---

charts/netbox/Chart.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/worker-deployment.yaml

Fix `initContainers` usage

---

README.md

README review proposal. This PR includes the following:
* Use OCI repo to simplify chart installation doc
* Drop DB password outdated recommendation (this is now properly managed via secrets)
* Upgrading notes moved to the end to promote configuration, as per most common standard
* More generic tone (mainly drop the `I`)
* Links fixes
* Formatting
> [!warning]
> The OCI package should be made public on the GHCR repo

Refresh readme content

---

README.md
charts/netbox/Chart.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/values.yaml

This option is not used by upstream anymore.
Ref: https://github.com/netbox-community/netbox-docker/pull/893

Drop skip startup scripts option

---

charts/netbox/Chart.yaml
charts/netbox/values.yaml

This PR fixes issue #267
Fixes
---
Fix the `values.yaml`

Fix values.yaml ref links

---

README.md
charts/netbox/Chart.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/worker-deployment.yaml
charts/netbox/values.yaml

* Main Netbox container, closes #177
* Worker & Cronjob containers, closes #163 and fixes #160
* By extent, support custom worker, fixes #130
(Also fix a tiny indentation issue in deployment)

Support overrides of all commands and args

---

charts/netbox/Chart.yaml
charts/netbox/templates/extra-deploy.yaml
charts/netbox/values.yaml

Hello,
This PR add extra deploy template.
extraDeploy value was already in values.yaml but the template did not exist.
I added an example in values.yaml.

Add support for extraDeploy

---

charts/netbox/Chart.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/tests/test-connection.yaml
charts/netbox/templates/worker-deployment.yaml

Indentations are a bit annoying, but this should fix hopefully all the issues.
I'm considering bumping indentation for lists to avoid further mismatch and streamline all numbers (not in this PR).
Closes #297 
Follow up of #294

Fix multiple indentation mismatches

---

charts/netbox/Chart.yaml
charts/netbox/templates/deployment.yaml

I'm assuming this is what was intended.

Fix `customReadinessProbe` check

---

README.md
charts/netbox/Chart.yaml
charts/netbox/values.yaml

Correct docs with latest secrets behavior

---

charts/netbox/Chart.yaml
charts/netbox/templates/_helpers.tpl

Using the feature provided by #299

Improve common image template

---

charts/netbox/Chart.yaml
charts/netbox/values.yaml

Fix wrong comment for `redis.enabled`

---

charts/netbox/Chart.yaml
charts/netbox/files/configuration.py
charts/netbox/files/ldap_config.py
charts/netbox/templates/configmap.yaml

Follow up of #327.
Extracted from #329, to highlight the fix for #340.
Closes #340 
Closes #284

Fix LDAP configuration ingestion

---

charts/netbox/Chart.yaml
charts/netbox/values.yaml

Add `allowPrivilegeEscalation` to additional `securityContext` values

---

README.md
charts/netbox/Chart.yaml
charts/netbox/values.yaml

Something went wrong on my end 😉 So old new PR.
Duplicates #368

Minor updates README

---

charts/netbox/Chart.yaml
charts/netbox/values.yaml

Add proper Redis CA mount examples

---

charts/netbox/Chart.yaml
charts/netbox/templates/_helpers.tpl
charts/netbox/templates/configmap.yaml
charts/netbox/templates/cronjob.yaml
charts/netbox/templates/deployment.yaml
charts/netbox/templates/worker/deployment.yaml

Ensure newlines and spaces are consistent
Fixes #376
Fixes #380

Fix extra config template rendering

---

charts/netbox/Chart.yaml
charts/netbox/files/ldap_config.py
pyproject.toml

Backward compatibility for LDAP require group

---

charts/netbox/Chart.yaml
charts/netbox/templates/_helpers.tpl

Discussed here: https://github.com/netbox-community/netbox-chart/commit/cdd50aeaacd2086b88c1bdb0f67b199e8f717ffa#r149868464

Fix incorrect format string template for `extraConfig` (`%s` -> `%d`)

---

charts/netbox/Chart.yaml
charts/netbox/README.md
charts/netbox/values.yaml

Improve Email secret documentation

---

charts/netbox/values.yaml

Add a note on insecure  `storageConfig`

---

charts/netbox/Chart.yaml
charts/netbox/templates/pvc.yaml

Ensure proper use of PVC annotations

---

charts/netbox/Chart.yaml
charts/netbox/files/ldap_config.py
charts/netbox/values.yaml

Thus fix the empty group issue.
Fixes #637

Provide better LDAP default values

---

charts/netbox/README.md
charts/netbox/templates/configmap.yaml
charts/netbox/values.schema.json
charts/netbox/values.yaml

See https://github.com/netbox-community/netbox/pull/18680
Fixes https://github.com/netbox-community/netbox-chart/issues/648
Ref https://netboxlabs.com/docs/netbox/en/stable/configuration/system/#storages

[v6] Drop deprecated storage values and introduce new value

---

charts/netbox/files/configuration.py
charts/netbox/templates/configmap.yaml
charts/netbox/values.schema.json
charts/netbox/values.yaml

Ref: https://netboxlabs.com/docs/netbox/en/stable/configuration/required-parameters/#databases

[v6] Support the `DATABASES` configuration key

---

charts/netbox/Chart.yaml
charts/netbox/README.md
charts/netbox/docs/prod.md

Just a stupid follow-up of #661, where the merges got wrong on this content. 🙄

Fix merge artifacts in documentation

---

charts/netbox/Chart.yaml
charts/netbox/templates/_helpers.tpl

Fixes https://github.com/netbox-community/netbox-chart/issues/709

Fix typo in the valkey-kv secret name

---

charts/netbox/Chart.yaml
charts/netbox/templates/configmap.yaml

Enhance `externalDatabase` configuration flexibility with templating

---

charts/netbox/Chart.yaml
charts/netbox/ci/pdb.yaml
charts/netbox/docs/prod.md
charts/netbox/templates/pdb.yaml
charts/netbox/templates/worker/pdb.yaml
charts/netbox/values.schema.json
charts/netbox/values.yaml

Add PodDisruptionBudget support for web and worker

---

charts/netbox/Chart.yaml
charts/netbox/docs/prod.md
charts/netbox/templates/configmap.yaml
charts/netbox/templates/pdb.yaml
charts/netbox/templates/worker/pdb.yaml
charts/netbox/values.schema.json
charts/netbox/values.yaml

* Breaking: Switch to Rancher `kubectl` #861 
* New values: PodDisruptionBudget #856 
* New feature: `externalDatabase` templating #855

Release v7.0.0
